//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anketa()
        {
            this.Pitanjes = new HashSet<Pitanje>();
            this.PopunjenaAnketas = new HashSet<PopunjenaAnketa>();
        }
    
        public int idAnketa { get; set; }
        public Nullable<int> idPredmet { get; set; }
        public Nullable<int> idNapravio { get; set; }
        public string napravioIme { get; set; }
        public System.DateTime datumKreiranja { get; set; }
        public string tipAnkete { get; set; }
        public string naziv { get; set; }
        public string opisAnkete { get; set; }
        public Nullable<System.DateTime> datumIstekaAnkete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pitanje> Pitanjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopunjenaAnketa> PopunjenaAnketas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Predmet Predmet { get; set; }
    }
}
