//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanoviGrupe
    {
        public int idVeza { get; set; }
        public Nullable<int> idAdministrator { get; set; }
        public Nullable<int> idGrupa { get; set; }
        public Nullable<int> idKorisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual GrupaChat GrupaChat { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
