//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanGrupe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClanGrupe()
        {
            this.ProjektniZadataks = new HashSet<ProjektniZadatak>();
        }
    
        public int idClanGrupe { get; set; }
        public int idStudent { get; set; }
        public int idGrupaProjekta { get; set; }
        public Nullable<bool> kreator { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual GrupaProjekta GrupaProjekta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektniZadatak> ProjektniZadataks { get; set; }
    }
}
