//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupaProjekta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupaProjekta()
        {
            this.ClanGrupes = new HashSet<ClanGrupe>();
        }
    
        public int idGrupaProjekta { get; set; }
        public int idProjekat { get; set; }
        public string nazivGrupe { get; set; }
        public Nullable<int> ostvareniBodovi { get; set; }
        public string komentarAsistenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanGrupe> ClanGrupes { get; set; }
        public virtual Projekat Projekat { get; set; }
    }
}
