//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IspitZabiljeska
    {
        public int idIspitZabiljeska { get; set; }
        public Nullable<int> idIspit { get; set; }
        public Nullable<int> idZabiljeska { get; set; }
    }
}
