//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ispit()
        {
            this.ispiti_rezultati = new HashSet<ispiti_rezultati>();
        }
    
        public int idIspit { get; set; }
        public int idProfesor { get; set; }
        public int idPredmet { get; set; }
        public Nullable<int> brojStudenata { get; set; }
        public string tipIspita { get; set; }
        public Nullable<System.DateTime> rokPrijave { get; set; }
        public string sala { get; set; }
        public Nullable<System.DateTime> termin { get; set; }
        public Nullable<int> vrijemeTrajanja { get; set; }
        public Nullable<int> kapacitet { get; set; }
        public string napomena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ispiti_rezultati> ispiti_rezultati { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
