//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Predmets = new HashSet<Predmet>();
            this.Predmets1 = new HashSet<Predmet>();
        }
    
        public int id { get; set; }
        public Nullable<int> idOdsjek { get; set; }
        public Nullable<int> idUloga { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public Nullable<System.DateTime> datumRodjenja { get; set; }
        public string JMBG { get; set; }
        public string email { get; set; }
        public string mjestoRodjenja { get; set; }
        public string kanton { get; set; }
        public string drzavljanstvo { get; set; }
        public string telefon { get; set; }
        public Nullable<bool> spol { get; set; }
        public string imePrezimeMajke { get; set; }
        public string imePrezimeOca { get; set; }
        public string adresa { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string linkedin { get; set; }
        public string website { get; set; }
        public byte[] fotografija { get; set; }
        public string indeks { get; set; }
        public string ciklus { get; set; }
        public string semestar { get; set; }
        public string titula { get; set; }
    
        public virtual Uloga Uloga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predmet> Predmets { get; set; }
        public virtual Odsjek Odsjek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predmet> Predmets1 { get; set; }
        public virtual Uloga Uloga1 { get; set; }
    }
}
