//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materijal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materijal()
        {
            this.Datotekes = new HashSet<Datoteke>();
        }
    
        public int idMaterijal { get; set; }
        public int idPredmet { get; set; }
        public int idTipMaterijala { get; set; }
        public Nullable<System.DateTime> datumObjave { get; set; }
        public Nullable<System.DateTime> datumIzmjene { get; set; }
        public string napomena { get; set; }
        public Nullable<bool> objavljeno { get; set; }
        public Nullable<int> sedmica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datoteke> Datotekes { get; set; }
        public virtual Predmet Predmet { get; set; }
        public virtual TipoviMaterijala TipoviMaterijala { get; set; }
    }
}
