//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MimeTip
    {
        public int idMimeTip { get; set; }
        public Nullable<int> idZadatak { get; set; }
        public string mimeTip1 { get; set; }
    
        public virtual Zadatak Zadatak { get; set; }
    }
}
