//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TYQcLL35gVEntities : DbContext
    {
        public TYQcLL35gVEntities()
            : base("name=TYQcLL35gVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Odsjek> Odsjeks { get; set; }
        public virtual DbSet<Predmet> Predmets { get; set; }
        public virtual DbSet<Privilegija> Privilegijas { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
        public virtual DbSet<odsjek_predmet> odsjek_predmet { get; set; }
    }
}
