//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovor
    {
        public int idOdgovor { get; set; }
        public int idPopunjenaAnketa { get; set; }
        public int idPitanje { get; set; }
        public int idPonudjeniOdgovor { get; set; }
        public string tekstOdgovora { get; set; }
    
        public virtual Pitanje Pitanje { get; set; }
        public virtual PonudjeniOdgovor PonudjeniOdgovor { get; set; }
        public virtual PopunjenaAnketa PopunjenaAnketa { get; set; }
    }
}
