//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class odsjek_predmet
    {
        public int idOdsjek { get; set; }
        public Nullable<int> idPredmet { get; set; }
        public string semestar { get; set; }
        public Nullable<bool> ciklus { get; set; }
        public Nullable<bool> tip { get; set; }
    
        public virtual Odsjek Odsjek { get; set; }
        public virtual Predmet Predmet { get; set; }
    }
}
