//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopunjenaAnketa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PopunjenaAnketa()
        {
            this.Odgovors = new HashSet<Odgovor>();
        }
    
        public int idPopunjenaAnketa { get; set; }
        public int idAnketa { get; set; }
        public int idPopunio { get; set; }
        public Nullable<System.DateTime> vrijemePopunjavanja { get; set; }
    
        public virtual Anketa Anketa { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odgovor> Odgovors { get; set; }
    }
}
