//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public int idPoruka { get; set; }
        public Nullable<int> idPosiljaoc { get; set; }
        public Nullable<int> idPrimaoc { get; set; }
        public Nullable<int> idGrupa { get; set; }
        public string sadrzajPoruke { get; set; }
        public byte[] file { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
    }
}
