//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozicija
    {
        public int idPozicija { get; set; }
        public Nullable<float> x1 { get; set; }
        public Nullable<float> x2 { get; set; }
        public Nullable<float> y1 { get; set; }
        public Nullable<float> y2 { get; set; }
    }
}
