//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predmet()
        {
            this.odsjek_predmet = new HashSet<odsjek_predmet>();
        }
    
        public int id { get; set; }
        public Nullable<int> idAsistent { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public string naziv { get; set; }
        public int ects { get; set; }
        public int brojPredavanja { get; set; }
        public int brojVjezbi { get; set; }
        public string opis { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odsjek_predmet> odsjek_predmet { get; set; }
    }
}
