//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projekat()
        {
            this.GrupaProjektas = new HashSet<GrupaProjekta>();
            this.ProjektniZadataks = new HashSet<ProjektniZadatak>();
        }
    
        public int idProjekat { get; set; }
        public Nullable<int> idKorisnik { get; set; }
        public Nullable<int> idPredmet { get; set; }
        public string nazivProjekta { get; set; }
        public Nullable<double> progress { get; set; }
        public string opisProjekta { get; set; }
        public Nullable<double> moguciBodovi { get; set; }
        public string rokProjekta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupaProjekta> GrupaProjektas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektniZadatak> ProjektniZadataks { get; set; }
    }
}
