//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektniFile
    {
        public int idProjektniFile { get; set; }
        public int idProjektniZadatak { get; set; }
        public byte[] file { get; set; }
        public Nullable<int> file_size { get; set; }
        public string file_type { get; set; }
        public string nazivFile { get; set; }
    
        public virtual ProjektniZadatak ProjektniZadatak { get; set; }
    }
}
