//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektniZadatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjektniZadatak()
        {
            this.ProjektniFiles = new HashSet<ProjektniFile>();
            this.ClanGrupes = new HashSet<ClanGrupe>();
        }
    
        public int idProjektnogZadatka { get; set; }
        public int idProjekta { get; set; }
        public string opis { get; set; }
        public string otkad { get; set; }
        public string dokad { get; set; }
        public Nullable<bool> zavrsen { get; set; }
        public string komentarAsistenta { get; set; }
    
        public virtual Projekat Projekat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektniFile> ProjektniFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClanGrupe> ClanGrupes { get; set; }
    }
}
