//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspored
    {
        public int idTermin { get; set; }
        public int idKabinet { get; set; }
        public int idGrupaTermin { get; set; }
        public string danUsedmici { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public string tipNastave { get; set; }
    
        public virtual GrupaTermina GrupaTermina { get; set; }
        public virtual GrupaTermina GrupaTermina1 { get; set; }
        public virtual Kabinet Kabinet { get; set; }
        public virtual Kabinet Kabinet1 { get; set; }
    }
}
