//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int idReply { get; set; }
        public int idComment { get; set; }
        public int idUserCreator { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> timeCreated { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
