//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sticky
    {
        public int idSticky { get; set; }
        public int idTheme { get; set; }
        public int idUser { get; set; }
        public Nullable<bool> set { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
