//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminZabiljeska
    {
        public int idTerminZabiljeska { get; set; }
        public Nullable<int> idTermin { get; set; }
        public Nullable<int> idZabiljeska { get; set; }
    
        public virtual Termin Termin { get; set; }
        public virtual Zabiljeska Zabiljeska { get; set; }
    }
}
