//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termin()
        {
            this.TerminZabiljeskas = new HashSet<TerminZabiljeska>();
        }
    
        public int idTermin { get; set; }
        public int idPredavac { get; set; }
        public int idPredmet { get; set; }
        public int idKabinet { get; set; }
        public string naziv { get; set; }
        public Nullable<int> danUSedmici { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public Nullable<int> trajanje { get; set; }
    
        public virtual Kabinet Kabinet { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminZabiljeska> TerminZabiljeskas { get; set; }
    }
}
