//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipFile
    {
        public int idTipFile { get; set; }
        public string tipFile1 { get; set; }
        public Nullable<int> idFile { get; set; }
    
        public virtual File File { get; set; }
    }
}
