//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class uloga_privilegija
    {
        public int idUloga { get; set; }
        public Nullable<int> idPrivilegija { get; set; }
        public long id_uloga { get; set; }
        public long id_privilegija { get; set; }
    
        public virtual Privilegija Privilegija { get; set; }
        public virtual Uloga Uloga { get; set; }
    }
}
