//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadatak()
        {
            this.MimeTips = new HashSet<MimeTip>();
        }
    
        public int idZadatak { get; set; }
        public Nullable<int> idZadaca { get; set; }
        public Nullable<int> redniBrojZadatkaUZadaci { get; set; }
        public Nullable<int> maxBrojBodova { get; set; }
        public Nullable<int> brojOstvarenihBodova { get; set; }
        public string profesorovKomentar { get; set; }
        public Nullable<System.DateTime> datumPredaje { get; set; }
        public string statusZadatka { get; set; }
        public byte[] sadrzajFile { get; set; }
        public Nullable<int> velicinaFile { get; set; }
        public string mimeTipUpdateZadatka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MimeTip> MimeTips { get; set; }
        public virtual Zadaca Zadaca { get; set; }
    }
}
