//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadatak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadatak()
        {
            this.Files = new HashSet<File>();
        }
    
        public int idZadatak { get; set; }
        public int idZadaca { get; set; }
        public string nazivZadatka { get; set; }
        public int maxBrojBodova { get; set; }
        public int brojOstvarenihBodova { get; set; }
        public string profesorovKomentar { get; set; }
        public System.DateTime datumPredaje { get; set; }
        public string statusZadatka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual Zadaca Zadaca { get; set; }
    }
}
