//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zadaca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadaca()
        {
            this.Zadataks = new HashSet<Zadatak>();
        }
    
        public int idZadaca { get; set; }
        public int idPredmet { get; set; }
        public string nazivZadace { get; set; }
        public int brojZadataka { get; set; }
        public System.DateTime rokZaPredaju { get; set; }
        public int maxBrojBodova { get; set; }
        public int ukupniOstvareniBodovi { get; set; }
        public byte[] postavkaZadace { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadatak> Zadataks { get; set; }
    }
}
