//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZahtjevZaPotvrdu
    {
        public int id { get; set; }
        public Nullable<int> idStudenta { get; set; }
        public Nullable<int> idSvrhe { get; set; }
        public Nullable<bool> obradjen { get; set; }
        public Nullable<System.DateTime> datumZahtjeva { get; set; }
        public Nullable<System.DateTime> datumObrade { get; set; }
        public Nullable<bool> besplatna { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual SvrhaPotvrde SvrhaPotvrde { get; set; }
    }
}
