//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracija.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZeljeniTermin
    {
        public int idZeljeniTermin { get; set; }
        public Nullable<int> idPredavac { get; set; }
        public Nullable<int> idKabinet { get; set; }
        public string danUSedmici { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
